### ISSUE TITLE
What makes this plugin better then official ANTLR Plugin?

### ISSUE THREAD

**Issue by xak2000** [Abnaxos/gradle-antlr4-plugin#3]
What makes this plugin better then [official ANTLR Plugin](https://docs.gradle.org/current/userguide/antlr_plugin.html)?
I mean what goal of this project? Why some will want to use this instead of official plugin? Maybe add some words about this in the readme section?

**Comment by Abnaxos** [comment]
Basically, it's said in the introduction:
-  When I made this, there was no support for ANTLR4 at all.
-  Directory structure: The original plugin produces a flat directory structure for the generated source files. These will be shown as error in IDEA, IMO rightly so. This plugin takes care that the files will be generated in a directory structure reflecting the package structure.
-  Pre-shadowing. This can be done using "traditional" shadowing, too – see the PreShadow plugin for details on why I prefer pre-shadowing. It's important to shadow antlr4-runtime because not doing so is basically begging for unresolvable version conflicts. The version of the runtime must match the version of the generator. If you've got two parsers generated with different versions of ANTLR, chances are that they cannot coexist in the same classpath because of a version conflict in antlr4-runtime.

It's possible that some of these points aren't valid anymore.

**Comment by xak2000** [comment]
Ok thanks for the explanation. Got it.
Also FYI official gradle plugin now preserves directory structure.

About pre-shadowing I doesn't fully understand what it is. I think it is needed only if I for example want to use antl3 + antl4 both in the same project?

**Comment by Abnaxos** [comment]
Shadowing (or shading in Maven) is moving a library to another package. For example, I move everything from org.antlr.v4.runtime to ch.raffael.myparser.thirdparty.antlr4rt, so I have well-known version of the library. The existing plugins (shadow plugin for Gradle, shade plugin for Maven) do that _after_ compilation. So, you write your code as usual using the original packages for your 3rd party libraries, and in the end, you move the libraries to another package. The source code is written against the unshadowed classes (e.g. `import org.antlr.v4.runtime.*`), after compilation, all references will be changed to the shadowed package.

Pre-shadowing, as I call it, does the shadowing _before_ compilation. The source code already uses the shadowed classes and will be compiled against them. The above import statement with pre-shadowing would be `ch.raffael.myparser.thirdparty.antlr4rt.*`.

I've originally had the idea when I was unable to shadow some library because I was using Java8 and the existing plugins could not handle that. The library, however, was compiled with target 1.6 → no problem for the shadow/shade plugins, if I could avoid having to transform my own Java8 source code. As a workaround, I inveted pre-shadowing. I liked that so much that I now always do it that way.

Shadowing in general is useful whenever you'd like to avoid unresolvable version conflicts, possibly also for users of your library. antlr4-runtime, asm and guava are commonly used libraries that are prone to cause problems. ANTLR3 and ANTLR4 is a bad example because of the "org.antlr._v4_.runtime" – these two runtimes are already separated. But ANTLR4 4.0 and ANTLR4 4.1 in one project won't work. This may also be caused by two external libraries that used different versions of ANTLR4 when generating the parser.

When version conflicts are to be expected, I usually shadow things preliminarily, so the users of the library won't have to deal with it. With ANTLR, version conflicts are almost predetermined.

**Comment by xak2000** [comment]
Ok got it. Big thanks to complete explanation.

I decide to stick with official plugin for now because I'm not writing library, I'm writing application. And if I change antlr4 version in the future (4.0 -> 4.1 for example) then my parsers will be regenerated with new version at `gradle build` step and my runtime will also use new antlr version. So there will be no conflicts I think.

But now I understand what problem this plugin resolve and if I ever stuck with this kind of problems - I know when to look at. :+1:
